# Linear Algebra Review

Phần này giúp các bạn ôn lại các kiến thức về Đại số tuyến tính và thao tác với ma trận dùng NumPy

# 1. Mở đầu

Trước hết cần cài đặt thư viện NumPy:

```sh
pip install numpy
```

In [19]:
import numpy as np
from numpy import linalg as la

## 2. Vector, Matrix

**Matrix**: Bảng chứa số

**Số chiều ma trận**: mxn (Dòng x cột)

**Vector**: Ma trận nx1 

In [5]:
m1 = np.array([[23,402],[69,221],[118,0]])
print("Matrix 1 = ", m1)
row, column = m1.shape
print("Matrix 1 row = ", row)
print("Matrix 1 column = ", column)

v1 = np.array([149 ,92 ,313])
print("Vector 1 = ", v1)
print("Vector 1 shape = ", v1.shape)

Matrix 1 =  [[ 23 402]
 [ 69 221]
 [118   0]]
Matrix 1 row =  3
Matrix 1 column =  2
Vector 1 =  [149  92 313]
Vector 1 shape =  (3,)


## 1.2. Các dạng ma trận và phép tính

### Ma trận 0

In [8]:
m_0 = np.zeros((3,5))
print(m_0)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ma trận 1

In [9]:
m_1 = np.ones((3,6))
print(m_1)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### Ma trận hằng

In [11]:
# tạo ma trận toàn số 8
m_c = np.full((4,6), 8)
print(m_c)

[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]


### Ma trận định danh

In [13]:
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Ma trận ngẫu nhiên

In [15]:
m_r = np.random.random((4,5))
print(m_r)

[[0.57504574 0.40085335 0.8996484  0.81593002 0.10781995]
 [0.52406657 0.31679267 0.93890609 0.29368056 0.97250091]
 [0.36366589 0.26401373 0.28767908 0.09642208 0.16994841]
 [0.10780838 0.6473732  0.03779623 0.40710676 0.42039904]]


### Slicing

Slice ma trận với NumPy chỉ tạo ra 1 view kháctro3 đến ma trận gốc, vì vậy modify ma trận đã slice sẽ modify ma trận gốc.

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

### Phép toán element-wise

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

### Nhân ma trận

Số cột ma trận 1 phải bằng dòng cột ma trận 2

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
print(v @ w)

### Sum 

In [17]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


### Chuyển vị

In [18]:
print(x.T)

[[1 3]
 [2 4]]


# 3. Các đặc trưng khác

## 3.1. Định thức

In [20]:
a = np.array([[5,2],[9,2]])
print(la.det(a))

-8.000000000000002


## 3.2. Hạng

In [23]:
h = np.array([[1,3,7],[2,8,3],[7,8,1]])
print(la.matrix_rank(h))

3


## 3.3. Nghịch đảo

In [27]:
print(la.pinv(h))

[[ 0.06694561 -0.22175732  0.19665272]
 [-0.07949791  0.20083682 -0.0460251 ]
 [ 0.16736402 -0.05439331 -0.0083682 ]]


## 3.4. Eigenvalues and eigenvectors

In [28]:
w, v = la.eig(np.array([[5,2],[9,2]]))

# Danh sách trị riêng
print("Eigenvalues: ")
print(w)
# Danh sách vector riêng
print("Eigenvectors: ")
print(v)

Eigenvalues: 
[ 8. -1.]
Eigenvectors: 
[[ 0.5547002  -0.31622777]
 [ 0.83205029  0.9486833 ]]


## 3.5. Norm

- [Norm](https://machinelearningcoban.com/math/#-norms-chuan)

In [29]:
print(la.norm(h))

15.811388300841896
